---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp main.css $DEPLOYPATH
    - /bin/cp main.js $DEPLOYPATH
    - /bin/cp terminal.js $DEPLOYPATH